### ISSUE TITLE
update LTWA to the 14/09/2017 version

### ISSUE THREAD

**Issue by Manu1400** [marcinwrochna/abbrevIso#2]
ie: words "beiešk-" is in this new version of LTWA

source: http://www.issn.org/services/online-services/access-to-the-ltwa/

**Comment by marcinwrochna** [comment]
Thanks for noticing! It should be fixed now.

For anyone interested, the process of getting the updated list was amusing – the website has an outdated .csv and even more outdated .pdf (of course!), so I tried scraping the html pages. Somehow after a few pages it starts throttling and serving one page (out of ~8500) per 2 seconds, and eventually it just disconnects. Even more weirdly, when I tried scraping from two different networks, one of them quickly got all pages that the other already had, and then they continued synchronously, throttled, eventually disconnecting. So there's some sort of caching, but given that each page has like <<1kb I can only imagine a poor guy switching floppy disks in the background. Hopeless.
The webpage is a mess, but I asked my brother and he quickly found some WordPress insecurities that allowed him to find the updated LTWA .csv hidden but public in a category named "(réservé à l’admin)". Phew!
